title: "Portfolio"
author:
  name: "Jason Swetzoff"
  email: 'jaswetz@gmail.com'
metadata:
  description: "Jason Swetzoff a Portland based UX designer."
  keywords: 'ux, designer, development, usability, ia, interactive, portfolio'
  copyright: 'Jason Swetzoff'
  author: 'Jason Swetzoff'
